---

apiVersion: v1
kind: Service
metadata:
  name: chat-amos-muchos
spec:
  selector:
    app: chat-amos-muchos
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-amos-muchos
spec:
  selector:
    matchLabels:
      app: chat-amos-muchos
  replicas: 1
  template:
    metadata:
      labels:
        app: chat-amos-muchos
    spec:
      containers:
      - name: chat-amos-muchos
        image: rg.fr-par.scw.cloud/breakathon-images/k8s-brk-fun-01:0.1
        ports:
        - containerPort: 5000
